Tracker:AddLocations("locations/AWESOME Shop.json")
Tracker:AddLocations("locations/Tier 1.json")
Tracker:AddLocations("locations/Tier 2.json")
Tracker:AddLocations("locations/Tier 3.json")
Tracker:AddLocations("locations/Tier 4.json")
Tracker:AddLocations("locations/Tier 5.json")
Tracker:AddLocations("locations/Tier 6.json")
Tracker:AddLocations("locations/Tier 7.json")
Tracker:AddLocations("locations/Tier 8.json")
Tracker:AddLocations("locations/Tier 9.json")
Tracker:AddLocations("locations/item_location_ref.json")
Tracker:AddLocations("locations/Alien Organisms.json")
Tracker:AddLocations("locations/Caterium.json")
Tracker:AddLocations("locations/Mycelia.json")
Tracker:AddLocations("locations/Nutrients.json")
Tracker:AddLocations("locations/Power Slugs.json")
Tracker:AddLocations("locations/Quartz.json")
Tracker:AddLocations("locations/Sulfur.json")
Tracker:AddLocations("locations/Alien Technology.json")
Tracker:AddLocations("locations/Hard Drive - Blue Crater.json")
Tracker:AddLocations("locations/Hard Drive - Red Bamboo Fields.json")
Tracker:AddLocations("locations/Hard Drive - Lake Forest.json")
Tracker:AddLocations("locations/Hard Drive - Red Jungle.json")
Tracker:AddLocations("locations/Hard Drive - Spire Coast.json")
Tracker:AddLocations("locations/Hard Drive - Swamp.json")
Tracker:AddLocations("locations/Hard Drive - Southern Forest.json")
Tracker:AddLocations("locations/Hard Drive - Titan Forest.json")
Tracker:AddLocations("locations/Hard Drive - Abyss Cliffs.json")
Tracker:AddLocations("locations/Hard Drive - Jungle Spires.json")
Tracker:AddLocations("locations/Hard Drive - Eastern Dune Forest.json")
Tracker:AddLocations("locations/Hard Drive - Maze Canyons.json")
Tracker:AddLocations("locations/Hard Drive - Desert Canyons.json")
Tracker:AddLocations("locations/Hard Drive - Crater Lakes.json")
Tracker:AddLocations("locations/Hard Drive - Dune Desert.json")
Tracker:AddLocations("locations/Hard Drive - Grass Fields.json")
Tracker:AddLocations("locations/Hard Drive - Rocky Desert.json")
Tracker:AddLocations("locations/Hard Drive - Snake Tree Forest.json")
Tracker:AddLocations("locations/Hard Drive - Western Beaches.json")
Tracker:AddLocations("locations/Hard Drive - Western Dune Forest.json")
Tracker:AddLocations("locations/Hard Drive - Northern Forest.json")