Tracker:AddLocations("locations/AWESOME Shop purchase 1.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 10.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 2.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 3.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 4.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 5.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 6.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 7.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 8.json")
Tracker:AddLocations("locations/AWESOME Shop purchase 9.json")
Tracker:AddLocations("locations/Alien Organisms.json")
Tracker:AddLocations("locations/Alien Technology.json")
Tracker:AddLocations("locations/Caterium.json")
Tracker:AddLocations("locations/Hard drive random check 1.json")
Tracker:AddLocations("locations/Hard drive random check 10.json")
Tracker:AddLocations("locations/Hard drive random check 100.json")
Tracker:AddLocations("locations/Hard drive random check 11.json")
Tracker:AddLocations("locations/Hard drive random check 12.json")
Tracker:AddLocations("locations/Hard drive random check 13.json")
Tracker:AddLocations("locations/Hard drive random check 14.json")
Tracker:AddLocations("locations/Hard drive random check 15.json")
Tracker:AddLocations("locations/Hard drive random check 16.json")
Tracker:AddLocations("locations/Hard drive random check 17.json")
Tracker:AddLocations("locations/Hard drive random check 18.json")
Tracker:AddLocations("locations/Hard drive random check 19.json")
Tracker:AddLocations("locations/Hard drive random check 2.json")
Tracker:AddLocations("locations/Hard drive random check 20.json")
Tracker:AddLocations("locations/Hard drive random check 21.json")
Tracker:AddLocations("locations/Hard drive random check 22.json")
Tracker:AddLocations("locations/Hard drive random check 23.json")
Tracker:AddLocations("locations/Hard drive random check 24.json")
Tracker:AddLocations("locations/Hard drive random check 25.json")
Tracker:AddLocations("locations/Hard drive random check 26.json")
Tracker:AddLocations("locations/Hard drive random check 27.json")
Tracker:AddLocations("locations/Hard drive random check 28.json")
Tracker:AddLocations("locations/Hard drive random check 29.json")
Tracker:AddLocations("locations/Hard drive random check 3.json")
Tracker:AddLocations("locations/Hard drive random check 30.json")
Tracker:AddLocations("locations/Hard drive random check 31.json")
Tracker:AddLocations("locations/Hard drive random check 32.json")
Tracker:AddLocations("locations/Hard drive random check 33.json")
Tracker:AddLocations("locations/Hard drive random check 34.json")
Tracker:AddLocations("locations/Hard drive random check 35.json")
Tracker:AddLocations("locations/Hard drive random check 36.json")
Tracker:AddLocations("locations/Hard drive random check 37.json")
Tracker:AddLocations("locations/Hard drive random check 38.json")
Tracker:AddLocations("locations/Hard drive random check 39.json")
Tracker:AddLocations("locations/Hard drive random check 4.json")
Tracker:AddLocations("locations/Hard drive random check 40.json")
Tracker:AddLocations("locations/Hard drive random check 41.json")
Tracker:AddLocations("locations/Hard drive random check 42.json")
Tracker:AddLocations("locations/Hard drive random check 43.json")
Tracker:AddLocations("locations/Hard drive random check 44.json")
Tracker:AddLocations("locations/Hard drive random check 45.json")
Tracker:AddLocations("locations/Hard drive random check 46.json")
Tracker:AddLocations("locations/Hard drive random check 47.json")
Tracker:AddLocations("locations/Hard drive random check 48.json")
Tracker:AddLocations("locations/Hard drive random check 49.json")
Tracker:AddLocations("locations/Hard drive random check 5.json")
Tracker:AddLocations("locations/Hard drive random check 50.json")
Tracker:AddLocations("locations/Hard drive random check 51.json")
Tracker:AddLocations("locations/Hard drive random check 52.json")
Tracker:AddLocations("locations/Hard drive random check 53.json")
Tracker:AddLocations("locations/Hard drive random check 54.json")
Tracker:AddLocations("locations/Hard drive random check 55.json")
Tracker:AddLocations("locations/Hard drive random check 56.json")
Tracker:AddLocations("locations/Hard drive random check 57.json")
Tracker:AddLocations("locations/Hard drive random check 58.json")
Tracker:AddLocations("locations/Hard drive random check 59.json")
Tracker:AddLocations("locations/Hard drive random check 6.json")
Tracker:AddLocations("locations/Hard drive random check 60.json")
Tracker:AddLocations("locations/Hard drive random check 61.json")
Tracker:AddLocations("locations/Hard drive random check 62.json")
Tracker:AddLocations("locations/Hard drive random check 63.json")
Tracker:AddLocations("locations/Hard drive random check 64.json")
Tracker:AddLocations("locations/Hard drive random check 65.json")
Tracker:AddLocations("locations/Hard drive random check 66.json")
Tracker:AddLocations("locations/Hard drive random check 67.json")
Tracker:AddLocations("locations/Hard drive random check 68.json")
Tracker:AddLocations("locations/Hard drive random check 69.json")
Tracker:AddLocations("locations/Hard drive random check 7.json")
Tracker:AddLocations("locations/Hard drive random check 70.json")
Tracker:AddLocations("locations/Hard drive random check 71.json")
Tracker:AddLocations("locations/Hard drive random check 72.json")
Tracker:AddLocations("locations/Hard drive random check 73.json")
Tracker:AddLocations("locations/Hard drive random check 74.json")
Tracker:AddLocations("locations/Hard drive random check 75.json")
Tracker:AddLocations("locations/Hard drive random check 76.json")
Tracker:AddLocations("locations/Hard drive random check 77.json")
Tracker:AddLocations("locations/Hard drive random check 78.json")
Tracker:AddLocations("locations/Hard drive random check 79.json")
Tracker:AddLocations("locations/Hard drive random check 8.json")
Tracker:AddLocations("locations/Hard drive random check 80.json")
Tracker:AddLocations("locations/Hard drive random check 81.json")
Tracker:AddLocations("locations/Hard drive random check 82.json")
Tracker:AddLocations("locations/Hard drive random check 83.json")
Tracker:AddLocations("locations/Hard drive random check 84.json")
Tracker:AddLocations("locations/Hard drive random check 85.json")
Tracker:AddLocations("locations/Hard drive random check 86.json")
Tracker:AddLocations("locations/Hard drive random check 87.json")
Tracker:AddLocations("locations/Hard drive random check 88.json")
Tracker:AddLocations("locations/Hard drive random check 89.json")
Tracker:AddLocations("locations/Hard drive random check 9.json")
Tracker:AddLocations("locations/Hard drive random check 90.json")
Tracker:AddLocations("locations/Hard drive random check 91.json")
Tracker:AddLocations("locations/Hard drive random check 92.json")
Tracker:AddLocations("locations/Hard drive random check 93.json")
Tracker:AddLocations("locations/Hard drive random check 94.json")
Tracker:AddLocations("locations/Hard drive random check 95.json")
Tracker:AddLocations("locations/Hard drive random check 96.json")
Tracker:AddLocations("locations/Hard drive random check 97.json")
Tracker:AddLocations("locations/Hard drive random check 98.json")
Tracker:AddLocations("locations/Hard drive random check 99.json")
Tracker:AddLocations("locations/Hub 1-1, item 1.json")
Tracker:AddLocations("locations/Hub 1-1, item 10.json")
Tracker:AddLocations("locations/Hub 1-1, item 2.json")
Tracker:AddLocations("locations/Hub 1-1, item 3.json")
Tracker:AddLocations("locations/Hub 1-1, item 4.json")
Tracker:AddLocations("locations/Hub 1-1, item 5.json")
Tracker:AddLocations("locations/Hub 1-1, item 6.json")
Tracker:AddLocations("locations/Hub 1-1, item 7.json")
Tracker:AddLocations("locations/Hub 1-1, item 8.json")
Tracker:AddLocations("locations/Hub 1-1, item 9.json")
Tracker:AddLocations("locations/Hub 1-2, item 1.json")
Tracker:AddLocations("locations/Hub 1-2, item 10.json")
Tracker:AddLocations("locations/Hub 1-2, item 2.json")
Tracker:AddLocations("locations/Hub 1-2, item 3.json")
Tracker:AddLocations("locations/Hub 1-2, item 4.json")
Tracker:AddLocations("locations/Hub 1-2, item 5.json")
Tracker:AddLocations("locations/Hub 1-2, item 6.json")
Tracker:AddLocations("locations/Hub 1-2, item 7.json")
Tracker:AddLocations("locations/Hub 1-2, item 8.json")
Tracker:AddLocations("locations/Hub 1-2, item 9.json")
Tracker:AddLocations("locations/Hub 1-3, item 1.json")
Tracker:AddLocations("locations/Hub 1-3, item 10.json")
Tracker:AddLocations("locations/Hub 1-3, item 2.json")
Tracker:AddLocations("locations/Hub 1-3, item 3.json")
Tracker:AddLocations("locations/Hub 1-3, item 4.json")
Tracker:AddLocations("locations/Hub 1-3, item 5.json")
Tracker:AddLocations("locations/Hub 1-3, item 6.json")
Tracker:AddLocations("locations/Hub 1-3, item 7.json")
Tracker:AddLocations("locations/Hub 1-3, item 8.json")
Tracker:AddLocations("locations/Hub 1-3, item 9.json")
Tracker:AddLocations("locations/Hub 1-4, item 1.json")
Tracker:AddLocations("locations/Hub 1-4, item 10.json")
Tracker:AddLocations("locations/Hub 1-4, item 2.json")
Tracker:AddLocations("locations/Hub 1-4, item 3.json")
Tracker:AddLocations("locations/Hub 1-4, item 4.json")
Tracker:AddLocations("locations/Hub 1-4, item 5.json")
Tracker:AddLocations("locations/Hub 1-4, item 6.json")
Tracker:AddLocations("locations/Hub 1-4, item 7.json")
Tracker:AddLocations("locations/Hub 1-4, item 8.json")
Tracker:AddLocations("locations/Hub 1-4, item 9.json")
Tracker:AddLocations("locations/Hub 1-5, item 1.json")
Tracker:AddLocations("locations/Hub 1-5, item 10.json")
Tracker:AddLocations("locations/Hub 1-5, item 2.json")
Tracker:AddLocations("locations/Hub 1-5, item 3.json")
Tracker:AddLocations("locations/Hub 1-5, item 4.json")
Tracker:AddLocations("locations/Hub 1-5, item 5.json")
Tracker:AddLocations("locations/Hub 1-5, item 6.json")
Tracker:AddLocations("locations/Hub 1-5, item 7.json")
Tracker:AddLocations("locations/Hub 1-5, item 8.json")
Tracker:AddLocations("locations/Hub 1-5, item 9.json")
Tracker:AddLocations("locations/Hub 10-1, item 1.json")
Tracker:AddLocations("locations/Hub 10-1, item 10.json")
Tracker:AddLocations("locations/Hub 10-1, item 2.json")
Tracker:AddLocations("locations/Hub 10-1, item 3.json")
Tracker:AddLocations("locations/Hub 10-1, item 4.json")
Tracker:AddLocations("locations/Hub 10-1, item 5.json")
Tracker:AddLocations("locations/Hub 10-1, item 6.json")
Tracker:AddLocations("locations/Hub 10-1, item 7.json")
Tracker:AddLocations("locations/Hub 10-1, item 8.json")
Tracker:AddLocations("locations/Hub 10-1, item 9.json")
Tracker:AddLocations("locations/Hub 10-2, item 1.json")
Tracker:AddLocations("locations/Hub 10-2, item 10.json")
Tracker:AddLocations("locations/Hub 10-2, item 2.json")
Tracker:AddLocations("locations/Hub 10-2, item 3.json")
Tracker:AddLocations("locations/Hub 10-2, item 4.json")
Tracker:AddLocations("locations/Hub 10-2, item 5.json")
Tracker:AddLocations("locations/Hub 10-2, item 6.json")
Tracker:AddLocations("locations/Hub 10-2, item 7.json")
Tracker:AddLocations("locations/Hub 10-2, item 8.json")
Tracker:AddLocations("locations/Hub 10-2, item 9.json")
Tracker:AddLocations("locations/Hub 10-3, item 1.json")
Tracker:AddLocations("locations/Hub 10-3, item 10.json")
Tracker:AddLocations("locations/Hub 10-3, item 2.json")
Tracker:AddLocations("locations/Hub 10-3, item 3.json")
Tracker:AddLocations("locations/Hub 10-3, item 4.json")
Tracker:AddLocations("locations/Hub 10-3, item 5.json")
Tracker:AddLocations("locations/Hub 10-3, item 6.json")
Tracker:AddLocations("locations/Hub 10-3, item 7.json")
Tracker:AddLocations("locations/Hub 10-3, item 8.json")
Tracker:AddLocations("locations/Hub 10-3, item 9.json")
Tracker:AddLocations("locations/Hub 10-4, item 1.json")
Tracker:AddLocations("locations/Hub 10-4, item 10.json")
Tracker:AddLocations("locations/Hub 10-4, item 2.json")
Tracker:AddLocations("locations/Hub 10-4, item 3.json")
Tracker:AddLocations("locations/Hub 10-4, item 4.json")
Tracker:AddLocations("locations/Hub 10-4, item 5.json")
Tracker:AddLocations("locations/Hub 10-4, item 6.json")
Tracker:AddLocations("locations/Hub 10-4, item 7.json")
Tracker:AddLocations("locations/Hub 10-4, item 8.json")
Tracker:AddLocations("locations/Hub 10-4, item 9.json")
Tracker:AddLocations("locations/Hub 10-5, item 1.json")
Tracker:AddLocations("locations/Hub 10-5, item 10.json")
Tracker:AddLocations("locations/Hub 10-5, item 2.json")
Tracker:AddLocations("locations/Hub 10-5, item 3.json")
Tracker:AddLocations("locations/Hub 10-5, item 4.json")
Tracker:AddLocations("locations/Hub 10-5, item 5.json")
Tracker:AddLocations("locations/Hub 10-5, item 6.json")
Tracker:AddLocations("locations/Hub 10-5, item 7.json")
Tracker:AddLocations("locations/Hub 10-5, item 8.json")
Tracker:AddLocations("locations/Hub 10-5, item 9.json")
Tracker:AddLocations("locations/Hub 2-1, item 1.json")
Tracker:AddLocations("locations/Hub 2-1, item 10.json")
Tracker:AddLocations("locations/Hub 2-1, item 2.json")
Tracker:AddLocations("locations/Hub 2-1, item 3.json")
Tracker:AddLocations("locations/Hub 2-1, item 4.json")
Tracker:AddLocations("locations/Hub 2-1, item 5.json")
Tracker:AddLocations("locations/Hub 2-1, item 6.json")
Tracker:AddLocations("locations/Hub 2-1, item 7.json")
Tracker:AddLocations("locations/Hub 2-1, item 8.json")
Tracker:AddLocations("locations/Hub 2-1, item 9.json")
Tracker:AddLocations("locations/Hub 2-2, item 1.json")
Tracker:AddLocations("locations/Hub 2-2, item 10.json")
Tracker:AddLocations("locations/Hub 2-2, item 2.json")
Tracker:AddLocations("locations/Hub 2-2, item 3.json")
Tracker:AddLocations("locations/Hub 2-2, item 4.json")
Tracker:AddLocations("locations/Hub 2-2, item 5.json")
Tracker:AddLocations("locations/Hub 2-2, item 6.json")
Tracker:AddLocations("locations/Hub 2-2, item 7.json")
Tracker:AddLocations("locations/Hub 2-2, item 8.json")
Tracker:AddLocations("locations/Hub 2-2, item 9.json")
Tracker:AddLocations("locations/Hub 2-3, item 1.json")
Tracker:AddLocations("locations/Hub 2-3, item 10.json")
Tracker:AddLocations("locations/Hub 2-3, item 2.json")
Tracker:AddLocations("locations/Hub 2-3, item 3.json")
Tracker:AddLocations("locations/Hub 2-3, item 4.json")
Tracker:AddLocations("locations/Hub 2-3, item 5.json")
Tracker:AddLocations("locations/Hub 2-3, item 6.json")
Tracker:AddLocations("locations/Hub 2-3, item 7.json")
Tracker:AddLocations("locations/Hub 2-3, item 8.json")
Tracker:AddLocations("locations/Hub 2-3, item 9.json")
Tracker:AddLocations("locations/Hub 2-4, item 1.json")
Tracker:AddLocations("locations/Hub 2-4, item 10.json")
Tracker:AddLocations("locations/Hub 2-4, item 2.json")
Tracker:AddLocations("locations/Hub 2-4, item 3.json")
Tracker:AddLocations("locations/Hub 2-4, item 4.json")
Tracker:AddLocations("locations/Hub 2-4, item 5.json")
Tracker:AddLocations("locations/Hub 2-4, item 6.json")
Tracker:AddLocations("locations/Hub 2-4, item 7.json")
Tracker:AddLocations("locations/Hub 2-4, item 8.json")
Tracker:AddLocations("locations/Hub 2-4, item 9.json")
Tracker:AddLocations("locations/Hub 2-5, item 1.json")
Tracker:AddLocations("locations/Hub 2-5, item 10.json")
Tracker:AddLocations("locations/Hub 2-5, item 2.json")
Tracker:AddLocations("locations/Hub 2-5, item 3.json")
Tracker:AddLocations("locations/Hub 2-5, item 4.json")
Tracker:AddLocations("locations/Hub 2-5, item 5.json")
Tracker:AddLocations("locations/Hub 2-5, item 6.json")
Tracker:AddLocations("locations/Hub 2-5, item 7.json")
Tracker:AddLocations("locations/Hub 2-5, item 8.json")
Tracker:AddLocations("locations/Hub 2-5, item 9.json")
Tracker:AddLocations("locations/Hub 3-1, item 1.json")
Tracker:AddLocations("locations/Hub 3-1, item 10.json")
Tracker:AddLocations("locations/Hub 3-1, item 2.json")
Tracker:AddLocations("locations/Hub 3-1, item 3.json")
Tracker:AddLocations("locations/Hub 3-1, item 4.json")
Tracker:AddLocations("locations/Hub 3-1, item 5.json")
Tracker:AddLocations("locations/Hub 3-1, item 6.json")
Tracker:AddLocations("locations/Hub 3-1, item 7.json")
Tracker:AddLocations("locations/Hub 3-1, item 8.json")
Tracker:AddLocations("locations/Hub 3-1, item 9.json")
Tracker:AddLocations("locations/Hub 3-2, item 1.json")
Tracker:AddLocations("locations/Hub 3-2, item 10.json")
Tracker:AddLocations("locations/Hub 3-2, item 2.json")
Tracker:AddLocations("locations/Hub 3-2, item 3.json")
Tracker:AddLocations("locations/Hub 3-2, item 4.json")
Tracker:AddLocations("locations/Hub 3-2, item 5.json")
Tracker:AddLocations("locations/Hub 3-2, item 6.json")
Tracker:AddLocations("locations/Hub 3-2, item 7.json")
Tracker:AddLocations("locations/Hub 3-2, item 8.json")
Tracker:AddLocations("locations/Hub 3-2, item 9.json")
Tracker:AddLocations("locations/Hub 3-3, item 1.json")
Tracker:AddLocations("locations/Hub 3-3, item 10.json")
Tracker:AddLocations("locations/Hub 3-3, item 2.json")
Tracker:AddLocations("locations/Hub 3-3, item 3.json")
Tracker:AddLocations("locations/Hub 3-3, item 4.json")
Tracker:AddLocations("locations/Hub 3-3, item 5.json")
Tracker:AddLocations("locations/Hub 3-3, item 6.json")
Tracker:AddLocations("locations/Hub 3-3, item 7.json")
Tracker:AddLocations("locations/Hub 3-3, item 8.json")
Tracker:AddLocations("locations/Hub 3-3, item 9.json")
Tracker:AddLocations("locations/Hub 3-4, item 1.json")
Tracker:AddLocations("locations/Hub 3-4, item 10.json")
Tracker:AddLocations("locations/Hub 3-4, item 2.json")
Tracker:AddLocations("locations/Hub 3-4, item 3.json")
Tracker:AddLocations("locations/Hub 3-4, item 4.json")
Tracker:AddLocations("locations/Hub 3-4, item 5.json")
Tracker:AddLocations("locations/Hub 3-4, item 6.json")
Tracker:AddLocations("locations/Hub 3-4, item 7.json")
Tracker:AddLocations("locations/Hub 3-4, item 8.json")
Tracker:AddLocations("locations/Hub 3-4, item 9.json")
Tracker:AddLocations("locations/Hub 3-5, item 1.json")
Tracker:AddLocations("locations/Hub 3-5, item 10.json")
Tracker:AddLocations("locations/Hub 3-5, item 2.json")
Tracker:AddLocations("locations/Hub 3-5, item 3.json")
Tracker:AddLocations("locations/Hub 3-5, item 4.json")
Tracker:AddLocations("locations/Hub 3-5, item 5.json")
Tracker:AddLocations("locations/Hub 3-5, item 6.json")
Tracker:AddLocations("locations/Hub 3-5, item 7.json")
Tracker:AddLocations("locations/Hub 3-5, item 8.json")
Tracker:AddLocations("locations/Hub 3-5, item 9.json")
Tracker:AddLocations("locations/Hub 4-1, item 1.json")
Tracker:AddLocations("locations/Hub 4-1, item 10.json")
Tracker:AddLocations("locations/Hub 4-1, item 2.json")
Tracker:AddLocations("locations/Hub 4-1, item 3.json")
Tracker:AddLocations("locations/Hub 4-1, item 4.json")
Tracker:AddLocations("locations/Hub 4-1, item 5.json")
Tracker:AddLocations("locations/Hub 4-1, item 6.json")
Tracker:AddLocations("locations/Hub 4-1, item 7.json")
Tracker:AddLocations("locations/Hub 4-1, item 8.json")
Tracker:AddLocations("locations/Hub 4-1, item 9.json")
Tracker:AddLocations("locations/Hub 4-2, item 1.json")
Tracker:AddLocations("locations/Hub 4-2, item 10.json")
Tracker:AddLocations("locations/Hub 4-2, item 2.json")
Tracker:AddLocations("locations/Hub 4-2, item 3.json")
Tracker:AddLocations("locations/Hub 4-2, item 4.json")
Tracker:AddLocations("locations/Hub 4-2, item 5.json")
Tracker:AddLocations("locations/Hub 4-2, item 6.json")
Tracker:AddLocations("locations/Hub 4-2, item 7.json")
Tracker:AddLocations("locations/Hub 4-2, item 8.json")
Tracker:AddLocations("locations/Hub 4-2, item 9.json")
Tracker:AddLocations("locations/Hub 4-3, item 1.json")
Tracker:AddLocations("locations/Hub 4-3, item 10.json")
Tracker:AddLocations("locations/Hub 4-3, item 2.json")
Tracker:AddLocations("locations/Hub 4-3, item 3.json")
Tracker:AddLocations("locations/Hub 4-3, item 4.json")
Tracker:AddLocations("locations/Hub 4-3, item 5.json")
Tracker:AddLocations("locations/Hub 4-3, item 6.json")
Tracker:AddLocations("locations/Hub 4-3, item 7.json")
Tracker:AddLocations("locations/Hub 4-3, item 8.json")
Tracker:AddLocations("locations/Hub 4-3, item 9.json")
Tracker:AddLocations("locations/Hub 4-4, item 1.json")
Tracker:AddLocations("locations/Hub 4-4, item 10.json")
Tracker:AddLocations("locations/Hub 4-4, item 2.json")
Tracker:AddLocations("locations/Hub 4-4, item 3.json")
Tracker:AddLocations("locations/Hub 4-4, item 4.json")
Tracker:AddLocations("locations/Hub 4-4, item 5.json")
Tracker:AddLocations("locations/Hub 4-4, item 6.json")
Tracker:AddLocations("locations/Hub 4-4, item 7.json")
Tracker:AddLocations("locations/Hub 4-4, item 8.json")
Tracker:AddLocations("locations/Hub 4-4, item 9.json")
Tracker:AddLocations("locations/Hub 4-5, item 1.json")
Tracker:AddLocations("locations/Hub 4-5, item 10.json")
Tracker:AddLocations("locations/Hub 4-5, item 2.json")
Tracker:AddLocations("locations/Hub 4-5, item 3.json")
Tracker:AddLocations("locations/Hub 4-5, item 4.json")
Tracker:AddLocations("locations/Hub 4-5, item 5.json")
Tracker:AddLocations("locations/Hub 4-5, item 6.json")
Tracker:AddLocations("locations/Hub 4-5, item 7.json")
Tracker:AddLocations("locations/Hub 4-5, item 8.json")
Tracker:AddLocations("locations/Hub 4-5, item 9.json")
Tracker:AddLocations("locations/Hub 5-1, item 1.json")
Tracker:AddLocations("locations/Hub 5-1, item 10.json")
Tracker:AddLocations("locations/Hub 5-1, item 2.json")
Tracker:AddLocations("locations/Hub 5-1, item 3.json")
Tracker:AddLocations("locations/Hub 5-1, item 4.json")
Tracker:AddLocations("locations/Hub 5-1, item 5.json")
Tracker:AddLocations("locations/Hub 5-1, item 6.json")
Tracker:AddLocations("locations/Hub 5-1, item 7.json")
Tracker:AddLocations("locations/Hub 5-1, item 8.json")
Tracker:AddLocations("locations/Hub 5-1, item 9.json")
Tracker:AddLocations("locations/Hub 5-2, item 1.json")
Tracker:AddLocations("locations/Hub 5-2, item 10.json")
Tracker:AddLocations("locations/Hub 5-2, item 2.json")
Tracker:AddLocations("locations/Hub 5-2, item 3.json")
Tracker:AddLocations("locations/Hub 5-2, item 4.json")
Tracker:AddLocations("locations/Hub 5-2, item 5.json")
Tracker:AddLocations("locations/Hub 5-2, item 6.json")
Tracker:AddLocations("locations/Hub 5-2, item 7.json")
Tracker:AddLocations("locations/Hub 5-2, item 8.json")
Tracker:AddLocations("locations/Hub 5-2, item 9.json")
Tracker:AddLocations("locations/Hub 5-3, item 1.json")
Tracker:AddLocations("locations/Hub 5-3, item 10.json")
Tracker:AddLocations("locations/Hub 5-3, item 2.json")
Tracker:AddLocations("locations/Hub 5-3, item 3.json")
Tracker:AddLocations("locations/Hub 5-3, item 4.json")
Tracker:AddLocations("locations/Hub 5-3, item 5.json")
Tracker:AddLocations("locations/Hub 5-3, item 6.json")
Tracker:AddLocations("locations/Hub 5-3, item 7.json")
Tracker:AddLocations("locations/Hub 5-3, item 8.json")
Tracker:AddLocations("locations/Hub 5-3, item 9.json")
Tracker:AddLocations("locations/Hub 5-4, item 1.json")
Tracker:AddLocations("locations/Hub 5-4, item 10.json")
Tracker:AddLocations("locations/Hub 5-4, item 2.json")
Tracker:AddLocations("locations/Hub 5-4, item 3.json")
Tracker:AddLocations("locations/Hub 5-4, item 4.json")
Tracker:AddLocations("locations/Hub 5-4, item 5.json")
Tracker:AddLocations("locations/Hub 5-4, item 6.json")
Tracker:AddLocations("locations/Hub 5-4, item 7.json")
Tracker:AddLocations("locations/Hub 5-4, item 8.json")
Tracker:AddLocations("locations/Hub 5-4, item 9.json")
Tracker:AddLocations("locations/Hub 5-5, item 1.json")
Tracker:AddLocations("locations/Hub 5-5, item 10.json")
Tracker:AddLocations("locations/Hub 5-5, item 2.json")
Tracker:AddLocations("locations/Hub 5-5, item 3.json")
Tracker:AddLocations("locations/Hub 5-5, item 4.json")
Tracker:AddLocations("locations/Hub 5-5, item 5.json")
Tracker:AddLocations("locations/Hub 5-5, item 6.json")
Tracker:AddLocations("locations/Hub 5-5, item 7.json")
Tracker:AddLocations("locations/Hub 5-5, item 8.json")
Tracker:AddLocations("locations/Hub 5-5, item 9.json")
Tracker:AddLocations("locations/Hub 6-1, item 1.json")
Tracker:AddLocations("locations/Hub 6-1, item 10.json")
Tracker:AddLocations("locations/Hub 6-1, item 2.json")
Tracker:AddLocations("locations/Hub 6-1, item 3.json")
Tracker:AddLocations("locations/Hub 6-1, item 4.json")
Tracker:AddLocations("locations/Hub 6-1, item 5.json")
Tracker:AddLocations("locations/Hub 6-1, item 6.json")
Tracker:AddLocations("locations/Hub 6-1, item 7.json")
Tracker:AddLocations("locations/Hub 6-1, item 8.json")
Tracker:AddLocations("locations/Hub 6-1, item 9.json")
Tracker:AddLocations("locations/Hub 6-2, item 1.json")
Tracker:AddLocations("locations/Hub 6-2, item 10.json")
Tracker:AddLocations("locations/Hub 6-2, item 2.json")
Tracker:AddLocations("locations/Hub 6-2, item 3.json")
Tracker:AddLocations("locations/Hub 6-2, item 4.json")
Tracker:AddLocations("locations/Hub 6-2, item 5.json")
Tracker:AddLocations("locations/Hub 6-2, item 6.json")
Tracker:AddLocations("locations/Hub 6-2, item 7.json")
Tracker:AddLocations("locations/Hub 6-2, item 8.json")
Tracker:AddLocations("locations/Hub 6-2, item 9.json")
Tracker:AddLocations("locations/Hub 6-3, item 1.json")
Tracker:AddLocations("locations/Hub 6-3, item 10.json")
Tracker:AddLocations("locations/Hub 6-3, item 2.json")
Tracker:AddLocations("locations/Hub 6-3, item 3.json")
Tracker:AddLocations("locations/Hub 6-3, item 4.json")
Tracker:AddLocations("locations/Hub 6-3, item 5.json")
Tracker:AddLocations("locations/Hub 6-3, item 6.json")
Tracker:AddLocations("locations/Hub 6-3, item 7.json")
Tracker:AddLocations("locations/Hub 6-3, item 8.json")
Tracker:AddLocations("locations/Hub 6-3, item 9.json")
Tracker:AddLocations("locations/Hub 6-4, item 1.json")
Tracker:AddLocations("locations/Hub 6-4, item 10.json")
Tracker:AddLocations("locations/Hub 6-4, item 2.json")
Tracker:AddLocations("locations/Hub 6-4, item 3.json")
Tracker:AddLocations("locations/Hub 6-4, item 4.json")
Tracker:AddLocations("locations/Hub 6-4, item 5.json")
Tracker:AddLocations("locations/Hub 6-4, item 6.json")
Tracker:AddLocations("locations/Hub 6-4, item 7.json")
Tracker:AddLocations("locations/Hub 6-4, item 8.json")
Tracker:AddLocations("locations/Hub 6-4, item 9.json")
Tracker:AddLocations("locations/Hub 6-5, item 1.json")
Tracker:AddLocations("locations/Hub 6-5, item 10.json")
Tracker:AddLocations("locations/Hub 6-5, item 2.json")
Tracker:AddLocations("locations/Hub 6-5, item 3.json")
Tracker:AddLocations("locations/Hub 6-5, item 4.json")
Tracker:AddLocations("locations/Hub 6-5, item 5.json")
Tracker:AddLocations("locations/Hub 6-5, item 6.json")
Tracker:AddLocations("locations/Hub 6-5, item 7.json")
Tracker:AddLocations("locations/Hub 6-5, item 8.json")
Tracker:AddLocations("locations/Hub 6-5, item 9.json")
Tracker:AddLocations("locations/Hub 7-1, item 1.json")
Tracker:AddLocations("locations/Hub 7-1, item 10.json")
Tracker:AddLocations("locations/Hub 7-1, item 2.json")
Tracker:AddLocations("locations/Hub 7-1, item 3.json")
Tracker:AddLocations("locations/Hub 7-1, item 4.json")
Tracker:AddLocations("locations/Hub 7-1, item 5.json")
Tracker:AddLocations("locations/Hub 7-1, item 6.json")
Tracker:AddLocations("locations/Hub 7-1, item 7.json")
Tracker:AddLocations("locations/Hub 7-1, item 8.json")
Tracker:AddLocations("locations/Hub 7-1, item 9.json")
Tracker:AddLocations("locations/Hub 7-2, item 1.json")
Tracker:AddLocations("locations/Hub 7-2, item 10.json")
Tracker:AddLocations("locations/Hub 7-2, item 2.json")
Tracker:AddLocations("locations/Hub 7-2, item 3.json")
Tracker:AddLocations("locations/Hub 7-2, item 4.json")
Tracker:AddLocations("locations/Hub 7-2, item 5.json")
Tracker:AddLocations("locations/Hub 7-2, item 6.json")
Tracker:AddLocations("locations/Hub 7-2, item 7.json")
Tracker:AddLocations("locations/Hub 7-2, item 8.json")
Tracker:AddLocations("locations/Hub 7-2, item 9.json")
Tracker:AddLocations("locations/Hub 7-3, item 1.json")
Tracker:AddLocations("locations/Hub 7-3, item 10.json")
Tracker:AddLocations("locations/Hub 7-3, item 2.json")
Tracker:AddLocations("locations/Hub 7-3, item 3.json")
Tracker:AddLocations("locations/Hub 7-3, item 4.json")
Tracker:AddLocations("locations/Hub 7-3, item 5.json")
Tracker:AddLocations("locations/Hub 7-3, item 6.json")
Tracker:AddLocations("locations/Hub 7-3, item 7.json")
Tracker:AddLocations("locations/Hub 7-3, item 8.json")
Tracker:AddLocations("locations/Hub 7-3, item 9.json")
Tracker:AddLocations("locations/Hub 7-4, item 1.json")
Tracker:AddLocations("locations/Hub 7-4, item 10.json")
Tracker:AddLocations("locations/Hub 7-4, item 2.json")
Tracker:AddLocations("locations/Hub 7-4, item 3.json")
Tracker:AddLocations("locations/Hub 7-4, item 4.json")
Tracker:AddLocations("locations/Hub 7-4, item 5.json")
Tracker:AddLocations("locations/Hub 7-4, item 6.json")
Tracker:AddLocations("locations/Hub 7-4, item 7.json")
Tracker:AddLocations("locations/Hub 7-4, item 8.json")
Tracker:AddLocations("locations/Hub 7-4, item 9.json")
Tracker:AddLocations("locations/Hub 7-5, item 1.json")
Tracker:AddLocations("locations/Hub 7-5, item 10.json")
Tracker:AddLocations("locations/Hub 7-5, item 2.json")
Tracker:AddLocations("locations/Hub 7-5, item 3.json")
Tracker:AddLocations("locations/Hub 7-5, item 4.json")
Tracker:AddLocations("locations/Hub 7-5, item 5.json")
Tracker:AddLocations("locations/Hub 7-5, item 6.json")
Tracker:AddLocations("locations/Hub 7-5, item 7.json")
Tracker:AddLocations("locations/Hub 7-5, item 8.json")
Tracker:AddLocations("locations/Hub 7-5, item 9.json")
Tracker:AddLocations("locations/Hub 8-1, item 1.json")
Tracker:AddLocations("locations/Hub 8-1, item 10.json")
Tracker:AddLocations("locations/Hub 8-1, item 2.json")
Tracker:AddLocations("locations/Hub 8-1, item 3.json")
Tracker:AddLocations("locations/Hub 8-1, item 4.json")
Tracker:AddLocations("locations/Hub 8-1, item 5.json")
Tracker:AddLocations("locations/Hub 8-1, item 6.json")
Tracker:AddLocations("locations/Hub 8-1, item 7.json")
Tracker:AddLocations("locations/Hub 8-1, item 8.json")
Tracker:AddLocations("locations/Hub 8-1, item 9.json")
Tracker:AddLocations("locations/Hub 8-2, item 1.json")
Tracker:AddLocations("locations/Hub 8-2, item 10.json")
Tracker:AddLocations("locations/Hub 8-2, item 2.json")
Tracker:AddLocations("locations/Hub 8-2, item 3.json")
Tracker:AddLocations("locations/Hub 8-2, item 4.json")
Tracker:AddLocations("locations/Hub 8-2, item 5.json")
Tracker:AddLocations("locations/Hub 8-2, item 6.json")
Tracker:AddLocations("locations/Hub 8-2, item 7.json")
Tracker:AddLocations("locations/Hub 8-2, item 8.json")
Tracker:AddLocations("locations/Hub 8-2, item 9.json")
Tracker:AddLocations("locations/Hub 8-3, item 1.json")
Tracker:AddLocations("locations/Hub 8-3, item 10.json")
Tracker:AddLocations("locations/Hub 8-3, item 2.json")
Tracker:AddLocations("locations/Hub 8-3, item 3.json")
Tracker:AddLocations("locations/Hub 8-3, item 4.json")
Tracker:AddLocations("locations/Hub 8-3, item 5.json")
Tracker:AddLocations("locations/Hub 8-3, item 6.json")
Tracker:AddLocations("locations/Hub 8-3, item 7.json")
Tracker:AddLocations("locations/Hub 8-3, item 8.json")
Tracker:AddLocations("locations/Hub 8-3, item 9.json")
Tracker:AddLocations("locations/Hub 8-4, item 1.json")
Tracker:AddLocations("locations/Hub 8-4, item 10.json")
Tracker:AddLocations("locations/Hub 8-4, item 2.json")
Tracker:AddLocations("locations/Hub 8-4, item 3.json")
Tracker:AddLocations("locations/Hub 8-4, item 4.json")
Tracker:AddLocations("locations/Hub 8-4, item 5.json")
Tracker:AddLocations("locations/Hub 8-4, item 6.json")
Tracker:AddLocations("locations/Hub 8-4, item 7.json")
Tracker:AddLocations("locations/Hub 8-4, item 8.json")
Tracker:AddLocations("locations/Hub 8-4, item 9.json")
Tracker:AddLocations("locations/Hub 8-5, item 1.json")
Tracker:AddLocations("locations/Hub 8-5, item 10.json")
Tracker:AddLocations("locations/Hub 8-5, item 2.json")
Tracker:AddLocations("locations/Hub 8-5, item 3.json")
Tracker:AddLocations("locations/Hub 8-5, item 4.json")
Tracker:AddLocations("locations/Hub 8-5, item 5.json")
Tracker:AddLocations("locations/Hub 8-5, item 6.json")
Tracker:AddLocations("locations/Hub 8-5, item 7.json")
Tracker:AddLocations("locations/Hub 8-5, item 8.json")
Tracker:AddLocations("locations/Hub 8-5, item 9.json")
Tracker:AddLocations("locations/Hub 9-1, item 1.json")
Tracker:AddLocations("locations/Hub 9-1, item 10.json")
Tracker:AddLocations("locations/Hub 9-1, item 2.json")
Tracker:AddLocations("locations/Hub 9-1, item 3.json")
Tracker:AddLocations("locations/Hub 9-1, item 4.json")
Tracker:AddLocations("locations/Hub 9-1, item 5.json")
Tracker:AddLocations("locations/Hub 9-1, item 6.json")
Tracker:AddLocations("locations/Hub 9-1, item 7.json")
Tracker:AddLocations("locations/Hub 9-1, item 8.json")
Tracker:AddLocations("locations/Hub 9-1, item 9.json")
Tracker:AddLocations("locations/Hub 9-2, item 1.json")
Tracker:AddLocations("locations/Hub 9-2, item 10.json")
Tracker:AddLocations("locations/Hub 9-2, item 2.json")
Tracker:AddLocations("locations/Hub 9-2, item 3.json")
Tracker:AddLocations("locations/Hub 9-2, item 4.json")
Tracker:AddLocations("locations/Hub 9-2, item 5.json")
Tracker:AddLocations("locations/Hub 9-2, item 6.json")
Tracker:AddLocations("locations/Hub 9-2, item 7.json")
Tracker:AddLocations("locations/Hub 9-2, item 8.json")
Tracker:AddLocations("locations/Hub 9-2, item 9.json")
Tracker:AddLocations("locations/Hub 9-3, item 1.json")
Tracker:AddLocations("locations/Hub 9-3, item 10.json")
Tracker:AddLocations("locations/Hub 9-3, item 2.json")
Tracker:AddLocations("locations/Hub 9-3, item 3.json")
Tracker:AddLocations("locations/Hub 9-3, item 4.json")
Tracker:AddLocations("locations/Hub 9-3, item 5.json")
Tracker:AddLocations("locations/Hub 9-3, item 6.json")
Tracker:AddLocations("locations/Hub 9-3, item 7.json")
Tracker:AddLocations("locations/Hub 9-3, item 8.json")
Tracker:AddLocations("locations/Hub 9-3, item 9.json")
Tracker:AddLocations("locations/Hub 9-4, item 1.json")
Tracker:AddLocations("locations/Hub 9-4, item 10.json")
Tracker:AddLocations("locations/Hub 9-4, item 2.json")
Tracker:AddLocations("locations/Hub 9-4, item 3.json")
Tracker:AddLocations("locations/Hub 9-4, item 4.json")
Tracker:AddLocations("locations/Hub 9-4, item 5.json")
Tracker:AddLocations("locations/Hub 9-4, item 6.json")
Tracker:AddLocations("locations/Hub 9-4, item 7.json")
Tracker:AddLocations("locations/Hub 9-4, item 8.json")
Tracker:AddLocations("locations/Hub 9-4, item 9.json")
Tracker:AddLocations("locations/Hub 9-5, item 1.json")
Tracker:AddLocations("locations/Hub 9-5, item 10.json")
Tracker:AddLocations("locations/Hub 9-5, item 2.json")
Tracker:AddLocations("locations/Hub 9-5, item 3.json")
Tracker:AddLocations("locations/Hub 9-5, item 4.json")
Tracker:AddLocations("locations/Hub 9-5, item 5.json")
Tracker:AddLocations("locations/Hub 9-5, item 6.json")
Tracker:AddLocations("locations/Hub 9-5, item 7.json")
Tracker:AddLocations("locations/Hub 9-5, item 8.json")
Tracker:AddLocations("locations/Hub 9-5, item 9.json")
Tracker:AddLocations("locations/Mycelia.json")
Tracker:AddLocations("locations/Nutrients.json")
Tracker:AddLocations("locations/Power Slugs.json")
Tracker:AddLocations("locations/Quartz.json")
Tracker:AddLocations("locations/Sulfur.json")
Tracker:AddLocations("locations/UpperBound.json")
Tracker:AddLocations("locations/Overworld.json")
