Tracker:AddLocations("locations/AWESOME Shop.json")
Tracker:AddLocations("locations/MAM.json")
Tracker:AddLocations("locations/Tier 1.json")
Tracker:AddLocations("locations/Tier 2.json")
Tracker:AddLocations("locations/Tier 3.json")
Tracker:AddLocations("locations/Tier 4.json")
Tracker:AddLocations("locations/Tier 5.json")
Tracker:AddLocations("locations/Tier 6.json")
Tracker:AddLocations("locations/Tier 7.json")
Tracker:AddLocations("locations/Tier 8.json")
Tracker:AddLocations("locations/Tier 9.json")
Tracker:AddLocations("locations/Overworld.json")
